version: '3'
services:
  movies:
    image: khadarbasha019/paytmrepomovies:latest
    ports:
      - "80:80"
    deploy:
      replicas: 3

  train:
    image: khadarbasha019/paytmrepotrain:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  dth:
    image: khadarbasha019/paytmrepodth:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  recharge:
    image: khadarbasha019/paytmreporecharge:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3
   movies:
    image: khadarbasha019/paytmrepomovies:latest
    ports:
      - "89:80"
    deploy:
      replicas: 3

 
