version: '3'
services:
    train:
    image: khadarbasha019/paytmrepotrain:latest
    ports:
      - "86:80"
    deploy:
      replicas: 3
    
 recharge:
    image: khadarbasha019/paytmreporecharge:latest
    ports:
      - "87:80"
    deploy:
      replicas: 3
      
      dth:
    image: khadarbasha019/paytmrepodth:latest
    ports:
      - "88:80"
    deploy:
      replicas: 3


   movies:
    image: khadarbasha019/paytmrepomovies:latest
    ports:
      - "89:80"
    deploy:
      replicas: 3

 
